spring:
  application:
    name: "ApiGateway"

server:
  port: 8083

gateway:
  routes:
    - path: /users/**
      url: http://localhost:8081
    - path: /notifications/**
      url: http://localhost:8082
